name: Eleventh Hour
favicon: null
layout_spectrum: 0.10368475317955017
typography_spectrum: 0.7796917776577175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.09129879949614406
  lightness: 0.4205165801104158
  saturation: 0.8531947615556419
  rhythmicContrast: 0.2741313714068383
purpose: []
